// src/routes/(app)/Schedule.svelte
<script lang="ts">
  import 'dayjs/locale/es'
  import dayjs from 'dayjs'
  import getFMSColor from '$lib/utils/getFMSColor'
  import type { PageServerData } from './$types'

  export let matchdays: PageServerData['matchdays']
</script>

<section class="my-11 text-sm font-semibold md:(my-16 text-base)">
  <h2 class="text-gradient tracking-wide">Próximas jornadas</h2>
  <span class="block h-px bg-brand-300 mt-3 mb-7 md:mb-9" />
  <div class="grid gap-7.5 sm:grid-cols-2 md:gap-10 lg:grid-cols-3">
    {#each matchdays as { fms, image, number, city, date }}
      {@const color = getFMSColor(fms.name)}
      <article
        class="aspect-2 flex items-end justify-between rounded-2 mr-8px mb-8px
          py-3 px-4 italic border-2 border-{color} shadow-{color}
          sm:last-of-type:hidden lg:last-of-type:flex"
        style:--image={`url(${image})`}
      >
        <div>
          <p>FMS {fms.name}</p>
          <p>Jornada {number}</p>
        </div>
        <div class="text-right">
          <p>{city}</p>
          <time datetime={date}>
            {dayjs(date).locale('es').format('ddd D MMMM')}
          </time>
        </div>
      </article>
    {/each}
  </div>
</section>

<style>
  article {
    background: linear-gradient(to top, theme('colors.brand.500'), transparent),
      var(--image) center;
    background-size: cover;
    box-shadow: 12px 12px 24px -6px theme('colors.brand.500'),
      8px 8px var(--un-shadow-color);
  }
</style>

// src/components/Schedule.tsx
import theme from '@/styles/_theme.module.scss'
import styles from '@/styles/Schedule.module.scss'
import type { Matchday } from '@/lib/types'
import formatDate from '@/lib/utils/formatDate'

interface Props {
  matchdays: Matchday[]
}

export default function Schedule({ matchdays }: Props) {
  return (
    <section className={styles.container}>
      <h2>Próximas jornadas</h2>
      <span />
      <div className={styles.matchdays}>
        {matchdays.map(({ id, league, number, city, date, image }) => (
          <article key={id}>
            <div>
              <p>FMS {league}</p>
              <p>Jornada {number}</p>
            </div>
            <div>
              <p>{city}</p>
              <p>{formatDate(date)}</p>
            </div>
            <style jsx>{`
              article {
                background: ${theme['bg-gradient']},
                  ${theme[`bg-${id.substring(0, 3)}`]}, url('${image}') center;
                background-size: cover;
              }
            `}</style>
          </article>
        ))}
      </div>
    </section>
  )
}
